### ISSUE TITLE
Поля MaxSpeed невозможно изменить

### ISSUE THREAD

**Issue by WinGKuza** [ext4zzzy/AbstractFactory-Example#3]
Есть поля MaxSpeed, интерфейс ITransport требует их реализации для разных классов.
Но проблема состоит в том, что если ты захочешь поменять это поле даже в самом классе, то у тебя не выйдет этого сделать тк поле имеет только метод get.
Если ты захочешь добавить хоть какие-то методы в этот проект, то возникнут проблемы с полями.
И зачем делать поля MaxSpeed public, а потом писать ещё один public метод GetMaxSpeed ? 
Любой человек и так сможет получить MaxSpeed без использования этого метода.

**Comment by ext4zzzy** [comment]
Во-первых это свойство🤓. Во-вторых зачем классу изменять это свойство? Если логика программы не подразумевает изменение этого свойства.  Свойство MaxSpeed можно, например передать как аргумент в некий метод, а вызов метода GetMaxSpeed просто выведет тебе строчку со значением. Ну как я понимаю, тебе нравится делать обработку в классах, где идет обращение к свойству или полю, а не написание отдельного метода который можно взывать в любом месте. А вообще тебе бы почитать о чем этот проект.

**Comment by WinGKuza** [comment]
Ну ты это сделал через АвтоПоле. Не совсем корректно это называть свойством.
Ты собираешься при расширении проекта полностью переписывать весь этот код?)
Ты понимаешь, что ты никак не поменяешь это поле даже в другом методе?

**Comment by TheActualTwinkle** [comment]
MaxSpeed => _maxSpeed
private int _maxSpeed

Вот и изменил свойство, называется инкапсуляция

Метод не возвращает MaxSpeed а принтит дату по красивому

**Comment by WinGKuza** [comment]
Ещё бы проверку сделать полей. И отлично

**Comment by WinGKuza** [comment]
Зачем человеку, который будет брать твой код переписывать его, чтобы у него что-то заработала? Ты же сам говорил про SOLID принципы. А получается твой код нельзя расширить без вмешательства в уже написанный код. Эти принципы SOLID и написаны, чтобы не нужно было разбираться что у тебя там написано, а просто взять готовое решение и использовать его.

**Comment by ext4zzzy** [comment]
Почитай о чём проект)

**Comment by ext4zzzy** [comment]
Почему нельзя расшрить?

**Comment by WinGKuza** [comment]
"Нельзя расширить без вмешательства в уже написанный код"

**Comment by ext4zzzy** [comment]
Ну скинь что там нельзя расширить
